// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// Import FirebaseOptions
// FirebaseOptions chứa cấu hình kết nối Firebase cho từng nền tảng
import 'package:flutter/foundation.dart'
// defaultTargetPlatform: biết app đang chạy trên nền tảng nào
// kIsWeb: kiểm tra có phải web không
// TargetPlatform: enum Android / iOS / Windows / macOS / Linux
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Getter static → gọi bằng:
    // DefaultFirebaseOptions.currentPlatform
    if (kIsWeb) {
      // Nếu app chạy trên Web
      throw UnsupportedError(
        // Ném lỗi vì project CHƯA cấu hình Firebase cho Web
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
    // Kiểm tra nền tảng hiện tại của app
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          // Project CHƯA cấu hình Firebase cho Windows
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          // Project CHƯA cấu hình Firebase cho Linux
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
      // Trường hợp nền tảng không xác định
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaC0dGJ1BvFfTAKUBtcyu02QaakIL-lP0',
    // API Key dùng để xác thực Firebase project
    appId: '1:672263626078:android:2dd6ac60e16f8b37c303cf',
    // ID ứng dụng Android trên Firebase
    messagingSenderId: '672263626078',
    // ID dùng cho Firebase Cloud Messaging (FCM)
    projectId: 'fir-login-588d4',
    // ID project Firebase
    storageBucket: 'fir-login-588d4.appspot.com',
    // Bucket dùng cho Firebase Storage
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAabyWABw40Pg1rEBvLbO3OG8aFZTwc3xA',
    // API Key cho iOS
    appId: '1:672263626078:ios:d959e9ca9aec36aac303cf',
    // ID ứng dụng iOS trên Firebase
    messagingSenderId: '672263626078',
    // FCM sender ID
    projectId: 'fir-login-588d4',
    // Firebase project ID
    storageBucket: 'fir-login-588d4.appspot.com',
    // Firebase Storage bucket
    iosBundleId: 'com.example.project',
    // Bundle ID của app iOS (PHẢI khớp với Xcode)
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAabyWABw40Pg1rEBvLbO3OG8aFZTwc3xA',
    // API Key cho macOS (thường giống iOS)
    appId: '1:672263626078:ios:d959e9ca9aec36aac303cf',
    // App ID cho macOS
    messagingSenderId: '672263626078',
    // FCM sender ID

    projectId: 'fir-login-588d4',
    // Firebase project ID

    storageBucket: 'fir-login-588d4.appspot.com',
    // Firebase Storage bucket
    iosBundleId: 'com.example.project',
    // Bundle ID cho macOS
  );

}